meta_product_name: "Flashcard"
meta_title: "Flashcard - Memorization, Simplified"
meta_description: "Flashcard, is a one stop shop where you can create your own modern flashcards to help you with your revision and studying. Whether your at school, university or learning while working."
meta_image: "flashcard-logo_hrqipb.png" # should exist in `app/assets/images/`
